#!/bin/bash

# Bash file to run test BE algorithm and check BW allocation/collision
# @author rouil

RES_DIR=res_test_be #output directory

if [ "$1" == "clean" ]; then
    rm -r $RES_DIR
else
	mkdir $RES_DIR
	cd $RES_DIR
	echo    "                       Packet sent | Packet received | BWR Collisions (SS side) | Collision (BS side)"
	for nbMNs in "1" "3" "5" "7" "10" "15" "20"; do		
		mkdir $nbMNs
		cd $nbMNs
		echo -n "Running for " $nbMNs "MNs:"
		ns ../../test-be.tcl $nbMNs &> log.t
		SENT=`grep WL_CBR out.res | grep -c ^s`
		RECV=`grep SNK_CBR out.res | grep -c ^r `
		BWR=`grep BWR out.res | grep -c ^D `
		COL=`grep COL out.res | grep -c ^D `
		echo    "      "$SENT"            "$RECV"                       "$BWR"                       "$COL"              "
		echo $nbMNs $SENT $RECV $BWR $COL >>../results.dat
		rm out.res
		rm log.t
		cd ..
		rm -r $nbMNs
	done
	cd ..
	gnuplot plot-test-be	
	echo "Simulation results in ./res_test_be/result.dat and plotted in ./test-be.eps"
fi
